name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number'
        required: true
        
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - run: msbuild VRChat-YT-DLP-Fix.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64
    - run: cp x64\Release\VRChat-YT-DLP-Fix.exe VRChat-YT-DLP-Fix.exe
    - run: 7z a -tzip VRChat-YT-DLP-Fix_${{ github.event.inputs.version }}.zip README.md VRChat-YT-DLP-Fix.exe
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "VRChat-YT-DLP-Fix_${{ github.event.inputs.version }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.version }}
        name: "${{ github.event.inputs.version }}"
        draft: true
        generateReleaseNotes: true
        artifactErrorsFailBuild: true

